const sampleProducts = [
  {
    name: "Coca Cola",
    price: 5000,
    description: "Refreshing cola drink 330ml",
    category: "Drinks",
    stock: 100,
    imageUrl: "/images/coca-cola.jpg",
  },
  {
    name: "Orange Juice",
    price: 7000,
    description: "Fresh orange juice 500ml",
    category: "Drinks",
    stock: 50,
    imageUrl: "/images/orange-juice.jpg",
  },
  {
    name: "Water Bottle",
    price: 3000,
    description: "Pure mineral water 600ml",
    category: "Drinks",
    stock: 200,
    imageUrl: "/images/water-bottle.jpg",
  },
  {
    name: "Green Tea",
    price: 6000,
    description: "Japanese green tea 350ml",
    category: "Drinks",
    stock: 75,
    imageUrl: "/images/green-tea.jpg",
  },
  {
    name: "Energy Drink",
    price: 8000,
    description: "Energy boost drink 250ml",
    category: "Drinks",
    stock: 60,
    imageUrl: "/images/energy-drink.jpg",
  },
  {
    name: "Potato Chips",
    price: 8000,
    description: "Crispy potato chips 150g",
    category: "Snacks",
    stock: 75,
    imageUrl: "/images/potato-chips.jpg",
  },
  {
    name: "Chocolate Bar",
    price: 12000,
    description: "Milk chocolate bar 100g",
    category: "Snacks",
    stock: 60,
    imageUrl: "/images/chocolate-bar.jpg",
  },
  {
    name: "Cookies",
    price: 9000,
    description: "Chocolate chip cookies 200g",
    category: "Snacks",
    stock: 80,
    imageUrl: "/images/cookies.jpg",
  },
  {
    name: "Nuts Mix",
    price: 15000,
    description: "Mixed nuts variety pack 250g",
    category: "Snacks",
    stock: 40,
    imageUrl: "/images/nuts-mix.jpg",
  },
  {
    name: "Candy Pack",
    price: 6000,
    description: "Assorted candy pack 150g",
    category: "Snacks",
    stock: 90,
    imageUrl: "/images/candy-pack.jpg",
  },
  {
    name: "Crackers",
    price: 7000,
    description: "Cheese crackers 180g",
    category: "Snacks",
    stock: 65,
    imageUrl: "/images/crackers.jpg",
  },
  {
    name: "Snack Bundle",
    price: 25000,
    description: "Mix of popular snacks (3 items)",
    category: "Bundle",
    stock: 30,
    imageUrl: "/images/snack-bundle.jpg",
  },
  {
    name: "Drink Bundle",
    price: 18000,
    description: "Combo of 3 different drinks",
    category: "Bundle",
    stock: 25,
    imageUrl: "/images/drink-bundle.jpg",
  },
  {
    name: "Party Bundle",
    price: 45000,
    description: "Perfect for parties (5 snacks + 3 drinks)",
    category: "Bundle",
    stock: 15,
    imageUrl: "/images/party-bundle.jpg",
  },
  {
    name: "Student Bundle",
    price: 20000,
    description: "Budget-friendly combo (2 snacks + 2 drinks)",
    category: "Bundle",
    stock: 35,
    imageUrl: "/images/student-bundle.jpg",
  },
];
